services:
  nginx:
    build:
      context: ./infra/
      args:
        BUILD_ARGUMENT_ENV: ${APP_ENV:-dev}
      dockerfile: ./nginx/Dockerfile
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html:ro,cached
      - ./infra/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      php:
        condition: service_started
    networks:
      - internal_network
      - proxy-net
    expose:
      - "80"
    environment:
      SERVER_NAME: "http://:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.group-2.rule=Host(`${HOST}`)"
      - "traefik.http.routers.group-2.entrypoints=websecure"
      - "traefik.http.routers.group-2.tls=true"
      - "traefik.http.services.group-2.loadbalancer.server.port=80"
      - "traefik.http.services.group-2.loadbalancer.server.scheme=http"
      - "traefik.docker.network=proxy-net"

  php:
    build:
      context: ./infra/
      dockerfile: ./php/Dockerfile
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html:cached
      - ./infra/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./infra/php/config/php.ini:/usr/local/etc/php/php.ini
      - ./infra/php/xdebug/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    depends_on:
      database:
        condition: service_healthy
    networks:
      - internal_network
    expose:
      - "9000"
      - "9003"

  database:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DTABASE_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${DATABASE_NAME:-group-2_db}
    volumes:
        - group-2_mysql:/var/lib/mysql:delegated
    networks:
        - internal_network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$$MYSQL_ROOT_PASSWORD",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  phpmyadmin:
      image: phpmyadmin/phpmyadmin:5
      environment:
          PMA_HOST: database
      depends_on:
          - database
      networks:
          - internal_network
          - proxy-net
      volumes:
          - group-2__db_admin_data:/var/www/html
      labels:
          - "traefik.enable=true"
          - "traefik.http.routers.group-2-pma.rule=Host(`${PMA_HOST}`)"
          - "traefik.http.routers.group-2-pma.entrypoints=websecure"
          - "traefik.http.routers.group-2-pma.tls=true"
          - "traefik.http.services.group-2-pma.loadbalancer.server.port=80"
          - "traefik.docker.network=proxy-net"

volumes:
    group-2__db_admin_data:
        name: group-2_db_admin_data
    group-2_mysql:
        name: group-2_mysql

networks:
    internal_network:
        name: internal_network_group-2
    proxy-net:
        name: proxy-net
        external: true
